name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 11 * * *'
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11
    steps:
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.${{ matrix.java }}"
    - uses: actions/checkout@v2.3.4
    - uses: coursier/cache-action@v5
    - run: |
        sbt -v publishLocal "project plugin" "^ scripted" &&
        java -jar ./target/scala-2.11/proguard/conscript-*.jar --version
